# analyzer/tickers.py

TICKER_GROUPS = {
    "Olie en Energie": ["TDW","SBLK","FRO","SM","NBR","OBE","VLO","VAL","BIR.TO","XOM","CVX","BP","TTE",
                        "BORR","VST","LNG","ENB", "AR","MPC","PDS","CLB","GTE","IPO.TO","OII","REI","RIG","BONTF"],
    "Nucleair en Uranium": ["CCJ","UEC","DNN","UUUU","NXE","GLO","EU","URG","UROY","NNE","DYL","MGA.TO","OKLO","FOSYF"],
    "Zilver": ["NEWP","DSVSF","AG","FSM","NUAG","CDE","EXK","HL","MAG","PAAS","SVM"],
    "Industrie en Mijnbouw": ["AEM","ASM","NEM","CNQ","CNIKF", "SU", "OU6.F", "LGO"],
    "Platina en PGM's": ["IMPUY","ANGPY","VALE","SBSW"],
    "Goud": ["TUD.V","NGD","EGO","BCM.V","CHPGF","ELRRF","TEUTF"],
    "Lithium": ["LAC","AMLIF","ABAT","FL.V","AMLI","GNENF","LI.V"],
    "Kool": ["AMR","METC","NC","WHC.AX","NRP"],
    "Koper": ["ERO","TGB","BHP","SFR.AX","TECK"],
}

TICKER_NAMES = {
    # Olie en Energie
    "TDW": "Tidewater Inc.",
    "SBLK": "Star Bulk Carriers Corp.",
    "FRO": "Frontline plc",
    "SM": "SM Energy Company",
    "NBR": "Nabors Industries Ltd.",
    "OBE": "Obsidian Energy Ltd.",
    "CLB": "Core Laboratories N.V.",
    "GTE": "Gran Tierra Energy Inc.",
    "HELIX": "Helix Energy Solutions Group Inc.",
    "IPO.TO": "InPlay Oil Corp.",
    "OII": "Oceaneering International Inc.",
    "REI": "Ring Energy Inc.",
    "RIG": "Transocean Ltd.",
    "VLO": "Valero Energy Corporation",
    "VAL": "Valaris Limited",
    "BIR.TO": "Birchcliff Energy Ltd.",
    "XOM": "Exxon Mobil Corporation",
    "CVX": "Chevron Corporation",
    "BP": "BP p.l.c.",
    "TTE": "TotalEnergies SE",
    "VST": "Vistra Corp.",
    "LNG": "Cheniere Energy, Inc.",
    "ENB": "Enbridge Inc.",
    "AR": "Antero Resources Corporation",
    "MPC": "Marathon Petroleum Corporation",
    "PDS": "Precision Drilling Corporation",
    "CRK": "Comstock Resources Inc.",
    "BTU": "Peabody Energy Corporation",

    # Nucleair en Uranium
    "CCJ": "Cameco Corporation",
    "UEC": "Uranium Energy Corp.",
    "DNN": "Denison Mines Corp.",
    "UUUU": "Energy Fuels Inc.",
    "NXE": "NexGen Energy Ltd.",
    "GLO": "Global Atomic Corp.",
    "EU": "Encore Energy Corp.",
    "URG": "Ur-Energy Inc.",
    "UROY": "Uranium Royalty Corp.",
    "DYL": "Deep Yellow Limited",
    "MGA.TO": "Mega Uranium Ltd.",
    "OKLO": "Oklo Inc.",
    "FOSYF": "Forsys Metals Corp.",

    # Zilver
    "NEWP": "New Pacific Metals Corp.",
    "DSVSF": "Discovery Silver Corp.",
    "AG": "First Majestic Silver Corp.",
    "FSM": "Fortuna Silver Mines Inc.",
    "NUAG": "New Pacific Metals (duplicate ticker)",
    "CDE": "Coeur Mining Inc.",
    "EXK": "Endeavour Silver Corp.",
    "HL": "Hecla Mining Company",
    "MAG": "MAG Silver Corp.",
    "PAAS": "Pan American Silver Corp.",
    "SVM": "Silvercorp Metals Inc.",

    # Industrie en Mijnbouw
    "AEM": "Agnico Eagle Mines Ltd.",
    "ASM": "Avino Silver & Gold Mines Ltd.",
    "NEM": "Newmont Corporation",
    "CNQ": "Canadian Natural Resources Ltd.",
    "CNIKF": "Canada Nickel Company Inc.",
    "SU": "Suncor Energy Inc.",
    "OU6.F": "Outokumpu Oyj (Frankfurt)",
    "LGO": "Largo Inc.",
    "IVN.TO": "Ivanhoe Mines Ltd.",
    "MTG": "Mount Gibson Iron Ltd.",
    "GERD": "Gerdau S.A.",
    "CSN": "Companhia Siderúrgica Nacional",
    "SID": "Companhia Siderúrgica Nacional ADR",
    "TERRACOM": "TerraCom Ltd.",
    "TDG": "Thungela Resources Ltd.",
    "FMG": "Fortescue Metals Group Ltd.",

    # Platina en PGM's
    "IMPUY": "Impala Platinum Holdings Ltd.",
    "ANGPY": "Anglo American Platinum Ltd.",
    "VALE": "Vale S.A.",
    "SBSW": "Sibanye Stillwater Ltd.",

    # Goud
    "TUD.V": "Tudor Gold Corp.",
    "NGD": "New Gold Inc.",
    "EGO": "Eldorado Gold Corp.",
    "BCM.V": "Bear Creek Mining Corp.",
    "CHPGF": "Chesapeake Gold Corp.",
    "ELRRF": "Eloro Resources Ltd.",
    "TEUTF": "Teuton Resources Corp.",
    "BRC": "Blackrock Silver Corp.",

    # Lithium
    "LAC": "Lithium Americas Corp.",
    "AMLIF": "American Lithium Corp.",
    "ABAT": "American Battery Technology Company",
    "FL.V": "Frontier Lithium Inc.",
    "AMLI": "American Lithium Minerals Inc.",
    "GNENF": "Ganfeng Lithium Group Co. Ltd.",
    "LI.V": "Standard Lithium Ltd.",
    "FRONT": "Frontier Lithium (duplicate ticker)",

    # Kool
    "AMR": "Alpha Metallurgical Resources Inc.",
    "METC": "Ramaco Resources Inc.",
    "NC": "Newcastle Coal Infrastructure Group",
    "WHC.AX": "Whitehaven Coal Ltd.",
    "NRP": "Natural Resource Partners L.P.",
    "NHC": "New Hope Corporation Ltd.",
}
